name: Hello World

on: 
    push:
        branches:
            - main

jobs:
    hello-job:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Test
              run: echo "Hello, world!"